version: "3.9"

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clicker
      POSTGRES_DB: clicker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: clicker
      DB_NAME: clicker
    ports:
      - "8081:8081"   # IMPORTANT : expose correctement
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8082:80"   # Nginx du front
    depends_on:
      - backend

  reverse_proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata: