version: "3.9"

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clicker
      POSTGRES_DB: clicker
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: clicker
      DB_NAME: clicker
      PORT: 8081

  frontend:
    build: ./frontend
    container_name: frontend_app

  reverse_proxy:
    image: nginx
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
